# Generated by Django 3.2.2 on 2021-05-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='limitdate',
            field=models.DateTimeField(),
        ),
    ]
