# Generated by Django 3.2.2 on 2021-05-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_limitdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='release',
        ),
        migrations.AlterField(
            model_name='article',
            name='adminonly',
            field=models.BooleanField(verbose_name='Admin only'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(max_length=2000, verbose_name="Corps de l'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='limitdate',
            field=models.DateTimeField(verbose_name='Date de péremption'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=60, verbose_name="Titre de l'article"),
        ),
    ]
