# Generated by Django 3.2.2 on 2021-05-07 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210507_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='release',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 12, 31, 28, 748088, tzinfo=utc)),
        ),
    ]
