# Generated by Django 3.1.2 on 2021-05-07 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='release',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 12, 42, 11, 233049, tzinfo=utc), verbose_name='Date de publication'),
        ),
    ]
